
apiVersion: v1
kind: ConfigMap
metadata:
  name: nezih-niegu-config
  labels:
    app: postgres
data:
  DEV_SECRET_KEY: healmint_okteto
  DEV_DATABASE: jfmfrteg 
  DEV_USER:	jfmfrteg 
  DEV_PASSWORD: RMVx-DWoNSyLJtlYD5C0TwLc4KfmvLMC
  DEV_HOST:  	hansken.db.elephantsql.com
  DEV_PORT: "5432"
