# Generated by Django 3.1.3 on 2022-12-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_entered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='entered_by',
        ),
    ]
