# Generated by Django 4.1.3 on 2022-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_remove_journal_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
